### ISSUE TITLE
dtype FOAMDataloader not set

### ISSUE THREAD

**Issue by JanisGeise** [AndreWeiner/flowtorch#50] opened 2024-07-30 13:45 UTC
Hi @AndreWeiner,

when passing a *dtype* as argument for the `FOAMDataloader`, it is not set correctly. For example in

    loader = FOAMDataloader(load_dir, dtype="pt.float64")
    print(_loader.vertices.dtype)

    # prints torch.float32

the type remains always the `DEFAULT_DTYPE`, independently whether passed as string or directly as, e.g. `pt.float64`. I'm assuming this issue affects the other `Dataloader` as well.

Further, in the `Dataloader`base class, the decorator `@abstractproperty` is depreciated according to the [Python documentation](https://docs.python.org/3.8/library/abc.html#abc.abstractproperty) and should be replaced with

    @property
    @abstractmethod

Regards,
Janis

**Comment by AndreWeiner** [comment] 2024-08-13 07:22
@JanisGeise the dtype passed to the constructor of FOAMDataloader was not correctly passed to the constructor of FOAMMesh. The problem is specific to this dataloader and should be fixed now (on the *aweiner* branch). Thanks for spotting this issue.
Best, Andre

**Closed as completed by AndreWeiner** 2024-08-13 07:22 UTC
